---

- hosts: web
  name: Web Server Installation
  become: yes
  tasks:
  - name: Installing Apache2 Packages
    apt: name=apache2 state=present

  - name: Start Apache2 Service
    service: name=apache2 state=started


- hosts: web
  name: NTP installation
  become: yes
  tasks:
  - name: Installing NTP Packages
    apt: name=ntp state=present


- hosts: web
  become: yes
  tasks:
  - name: Checking Kernel Details
    command: 'uname -a'

